### PR TITLE
Refactor Full SDK (without major changes)

### LINKED ISSUE #37: Autoload PSR-4 failed
### General information

* SDK/Library version: 1.0.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP Windows 10

### Issue description

I can't autoload files without composer.
**index.php**
```php
<?php

require __DIR__ . '\autoload.php';

use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;
// Creating an environment
$clientId = "xxx";
$clientSecret = "xxx";

$environment = new SandboxEnvironment($clientId, $clientSecret);
$client = new PayPalHttpClient($environment);
```
**autoload.php**
```php
<?php
/**
 * An example of a project-specific implementation.
 *
 * After registering this autoload function with SPL, the following line
 * would cause the function to attempt to load the \Foo\Bar\Baz\Qux class
 * from /path/to/project/src/Baz/Qux.php:
 *
 *      new \Foo\Bar\Baz\Qux;
 *
 * @param string $class The fully-qualified class name.
 * @return void
 */
spl_autoload_register(function ($class) {

    // project-specific namespace prefix
    $prefix = 'PayPalCheckoutSdk\\';

    // base directory for the namespace prefix
    $base_dir = __DIR__ . '\\PayPalCheckoutSdk\\';

    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relative_class = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = $base_dir . str_replace('\\', '\\', $relative_class) . '.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }
});
```
With this autoloader 2 files has been successfully loaded:

> C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\SandboxEnvironment.php
> C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\PayPalEnvironment.php

And next step is trying load this class:
**PayPalHttp\Environment**
with error:

> Fatal error: Interface 'PayPalHttp\Environment' not found in C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\PayPalEnvironment.php on line 7

### PR DESCRIPTION
**Pull request by 22h**
### Composer
- remove composer.phar
- add install informations into README.md (compoer require etc.)

### Testing
- restructuring of the tests
- grouping of the test in integration and unit tests (IntegrationTestCase and UnitTestCase)
- add unit tests
- rename phpunit.xml into phpunit.xml.dist and add phpunit.xml to gitignore
- remove ini_set from TestHarness (now IntegrationTestCase) and add this to phpunit.xml.dist
- also add env vars for client id and secret to phpunit.xml.dist

### Code
- add phpDocs for all methods (in lib/PayPalCheckoutSdk)
- minimize code redundancy with traits, but change not interfaces for 100% compatibility

### Braintree
A few words. I have removed the Braintree headers, because the files have already been changed before without modifying the hash.

### More tests
I would also like to write more tests, but it is not possible (\PayPalHttp\HttpClient::execute) to mock. Maybe I'll make a merge request there if everything went fine here.

### Fixes
#37 #27

### CODE REVIEW

**Comment by 22h** [comment]
*push*

**Review by omar09091993 — APPROVED** [review]

**Comment by lloricode** [comment]
@22h this is good since you followed [PSR](https://www.php-fig.org/psr/)

**Review by lloricode — APPROVED** [review]

**Comment by lloricode** [comment]
also add gitattributes #64, but this is base on develop

**Review by omar09091993 — APPROVED** [review]

**Review by omar09091993 — APPROVED** [review]

**Comment by 22h** [comment]
@lloricode 
I am currently on holiday, I would be happy to include your changes the week after next. Is that all right with you?

As long as no one takes the MR, there's no point.....

**Comment by lloricode** [comment]
> @lloricode
> I am currently on holiday, I would be happy to include your changes the week after next. Is that all right with you?
> 
> As long as no one takes the MR, there's no point.....

yes it would help

**Comment by lloricode** [comment]
@22h can you pull latest branch to here

**Review by lloricode — APPROVED** [review]

**Comment by 22h** [comment]
@lloricode sry for late response, done.

**Comment by lloricode** [comment]
+1

**Comment by lloricode** [comment]
any plan for this?

**Comment by 22h** [comment]
nop, i waiting for... review from paypal, maybe? i have no idea, its a little bit boring

**Comment by phpfui** [comment]
Would it be possible to remove the Sample namespace from the autoloader?  It is not needed and actually might conflict with something.  Just removing the line from the composer.json is all that is needed. Not a source change.

**Comment by magnusreiss** [comment]
The samples are not in autoload, only the tests. I can move the testing namespace into autoload-dev

**Comment by phpfui** [comment]
It appears the tests are already in the autoload-dev section.  I was referring to the Samples in the regular autoload section.

```json
    "autoload": {
        "psr-4": {
            "PayPalCheckoutSdk\\": "lib/PayPalCheckoutSdk",
            "Sample\\":"samples/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Test\\":"tests/"
        }
    },
```

The Sample\\ line should be removed.

Thanks for doing this, I would submit a PR, but figured it might be better just to use an open PR that is doing general cleanup.

**Comment by magnusreiss** [comment]
Oh thanks, I overlooked it while editing. I update it soon

**Comment by lloricode** [comment]
I don't know if this possible to merge, i seems maintainer did not care this PR

**Comment by magnusreiss** [comment]
Yes, but i have no idea why. Meanwhile I do not even need this SDK anymore

**Comment by heangpov16** [comment]
Support money

**Review by heangpov16 — COMMENTED** [review]
Support money

**Comment by Cordelro86** [comment]
Payout

**Comment by crookedneighbor** [comment]
This SDK is deprecated. See: https://github.com/paypal/Checkout-PHP-SDK/commit/c8b2df6fe3f25dd643e46b463d672739140ddef4

**Pull request closed without merging**
