### PR TITLE
Add .gitattributes to exclude on production

### PR DESCRIPTION
**Pull request by lloricode**
Signed-off-by: Lloric Mayuga Garcia <lloricode@gmail.com>

### CODE REVIEW

**Comment by lloricode** [comment]
+1

**Review by simonschaufi — APPROVED** [review]

**Comment by simonschaufi** [comment]
@rajarampadmanathan @mstuart review please ;)

**Review by Wiatt99923 — APPROVED** [review]

**Comment by Iamvhelle** [comment]
.gitattributes

**Review by Cordelro86 — APPROVED** [review]

**Comment by ankurk91** [comment]
Glad to see some progress on this PR

**Review by ankurk91 — APPROVED** [review]

**Comment by crookedneighbor** [comment]
This SDK is deprecated. See: https://github.com/paypal/Checkout-PHP-SDK/commit/c8b2df6fe3f25dd643e46b463d672739140ddef4

**Pull request closed without merging**
